/* GENERATED by docs/build-lube-tds.py — do not edit by hand.

   Published figures off the suppliers' data sheets. A property the sheet does
   not state is null and stays null.

   `pour` is the ASTM D97 pour point and NOTHING ELSE. It is not the coldest
   morning the machine may be started on — that is cold-crank and pumpability
   for an engine oil, whether the oil throws for a splash gearbox, whether the
   pump can draw for a hydraulic system. Treating it as an operating limit is
   the mistake this file exists to make harder, so the API below will tell you
   a product is DISQUALIFIED when its pour point is at or above the design
   minimum, and will never tell you one is approved.
*/
(function(w){
  "use strict";
var TDS = [];
var DESIGN_MIN = -40;

  var CYR = {"ЛУКОЙЛ":"LUKOIL","ПОЛИФЛЕКС":"POLYFLEX","СИНТОФЛЕКС":"SYNTOFLEX",
             "КАРБОФЛЕКС":"CARBOFLEX","АРКТИК":"ARCTIC","ЕР":"EP"};
  var SPELL = {SYNTHOFLEX:"SYNTOFLEX",POLIFLEX:"POLYFLEX",
               KARBOFLEX:"CARBOFLEX",SINTOFLEX:"SYNTOFLEX"};
  var NOISE = {OIL:1,GREASE:1,LUBRICANT:1,FLUID:1,TDS:1,EN:1,RU:1,ENG:1,
               TZK:1,DATA:1,SHEET:1,TECHNICAL:1,PRODUCT:1,HD:1,NEW:1};
  function toks(name){
    var n = String(name||"").toUpperCase(), k;
    for(k in CYR) n = n.split(k).join(CYR[k]);
    n = n.replace(/\b(\d+)W\s*-?\s*(\d+)\b/g, "$1W$2")
         .replace(/[^A-Z0-9]+/g, " ");
    var out = {};
    n.split(" ").forEach(function(t){
      t = SPELL[t] || t;
      if(t && !NOISE[t]) out[t] = 1;
    });
    return out;
  }
  function subset(a,b){
    for(var k in a) if(!b[k]) return false;
    return true;
  }
  w.LUBETDS = {
    all: TDS,
    designMin: DESIGN_MIN,
    /* The sheet for a product, matched the way the catalogue matches: one
       token set containing the other, with a floor of two shared tokens so a
       brand name alone is never an identification. */
    of: function(name){
      var t = toks(name), n = 0, k;
      for(k in t) n++;
      if(n < 2) return null;
      var hits = TDS.filter(function(r){
        var s = toks(r.p), m = 0, kk;
        for(kk in s) m++;
        if(m < 2) return false;
        return m <= n ? subset(s, t) : subset(t, s);
      });
      if(!hits.length) return null;
      hits.sort(function(a,b){ return b.p.length - a.p.length; });
      return hits[0];
    },
    /* Never "approved". Either the sheet disqualifies the product outright, or
       nobody has established that it is fit — which is a question for the
       engineer, not a green tick from a parser. */
    coldVerdict: function(name){
      var r = this.of(name);
      if(!r) return { k:"nosheet" };
      if(r.pour == null) return { k:"nopour", r:r };
      if(r.pour >= DESIGN_MIN) return { k:"toowarm", pour:r.pour, r:r };
      return { k:"pourbelow", pour:r.pour, r:r };
    },
    count: function(){ return TDS.length; }
  };
})(typeof window !== "undefined" ? window : this);
