#!/usr/bin/env python3
"""
Build the dashboard data by SCANNING A PHOTO FOLDER -- no Excel required.

This is the command-line equivalent of the dashboard's "Open photo folder"
button. Use it when you want to regenerate the bundled/shareable data file
(data/magnetic_plug.js) from a folder of photos, e.g. to refresh a copy you
send to someone, or if you use a browser without the folder picker.

Expected folder layout:

    <PhotosRoot>/
        TK146/                      # truck / equipment
            2026-10-15/             # inspection date (YYYY-MM-DD)
                4C.jpg              # one photo per plug position (4C/4D/4E/4F)
                4D.jpg  4E.jpg  4F.jpg
            2026-07-29/ ...
        TK147/ ...

Also accepted: flat file names like  TK146_4C_2026-10-15.jpg, and an optional
grade suffix like  4C_C.jpg  or  TK146_4C_2026-10-15_C.jpg.

Usage:
    python ingest/scan_photos.py "N:/Condition Monitoring/Magnetic Plug/Photos"
    python ingest/scan_photos.py ./Photos --copy      # copy photos into assets/photos/
"""
from __future__ import annotations
import argparse, json, os, re, shutil, sys

HERE = os.path.dirname(os.path.abspath(__file__))
REPO = os.path.dirname(HERE)
PHOTO_DIR = os.path.join(REPO, "assets", "photos")
DATA_FILE = os.path.join(REPO, "data", "magnetic_plug.js")

IMG_RE = re.compile(r"\.(jpe?g|png|webp|gif|bmp)$", re.I)
DATE_RE = re.compile(r"(20\d{2})[-_.]?(\d{2})[-_.]?(\d{2})|(\d{2})[-_.](\d{2})[-_.](20\d{2})")
POS_RE = re.compile(r"(4[CDEF])", re.I)
GRADE_RE = re.compile(r"[_\-\s]([ABCDX])(?=[_\-.\s]|$)", re.I)
EQUIP_RE = re.compile(r"(?:^|[_\-.\s])([A-Za-z]{1,4}\d+)(?=[_\-.\s]|$)")

POS_LABELS = {"4C": "Left Rear Final Drive", "4D": "Right Rear Final Drive",
              "4E": "Left Rear Final Drive", "4F": "Right Rear Final Drive"}
POS_ORDER = ["4C", "4D", "4E", "4F"]


def parse_date(s):
    m = DATE_RE.search(s or "")
    if not m:
        return None
    return f"{m[1]}-{m[2]}-{m[3]}" if m[1] else f"{m[6]}-{m[5]}-{m[4]}"


def parse_pos(s):
    m = POS_RE.search(s or "")
    return m.group(1).upper() if m else None


def parse_grade(name):
    m = GRADE_RE.search(name or "")
    return m.group(1).upper() if m else None


def parse_equip(s):
    m = EQUIP_RE.search(s or "")
    return m.group(1).upper() if m else None


def scan(root, copy):
    """Walk the tree; infer (equip, date, position) from folder names then file names."""
    records = {}   # (equip, date) -> record
    if copy:
        os.makedirs(PHOTO_DIR, exist_ok=True)

    for dirpath, _dirs, files in os.walk(root):
        rel_parts = os.path.relpath(dirpath, root).split(os.sep)
        # infer equipment + date from the folder path
        ctx_equip = next((p.upper().replace(" ", "") for p in rel_parts
                          if re.match(r"^[A-Za-z]{1,4}\s?\d+$", p)), None)
        ctx_date = next((parse_date(p) for p in rel_parts if parse_date(p)), None)

        for fn in sorted(files):
            if not IMG_RE.search(fn):
                continue
            equip = ctx_equip or parse_equip(fn) or "UNKNOWN"
            date = ctx_date or parse_date(fn) or ""
            rk = (equip, date)
            rec = records.setdefault(rk, {"equipment": equip, "date": date, "motorHours": None,
                                          "source": "photo folder", "positions": []})
            pos = parse_pos(fn) or parse_pos(dirpath) or (POS_ORDER[len(rec["positions"])]
                                                          if len(rec["positions"]) < 4 else f"P{len(rec['positions'])+1}")
            # one photo per plug position — skip duplicates (e.g. an "_MP" copy)
            if any(p["key"] == pos for p in rec["positions"]):
                continue
            grade = parse_grade(fn)
            src = os.path.join(dirpath, fn)
            if copy:
                ext = os.path.splitext(fn)[1].lower() or ".jpg"
                out_name = f"{equip}_{pos}_{date or 'nodate'}{ext}"
                shutil.copy2(src, os.path.join(PHOTO_DIR, out_name))
                photo = f"assets/photos/{out_name}"
            else:
                photo = os.path.abspath(src).replace("\\", "/")
            rec["positions"].append({
                "key": pos, "label": POS_LABELS.get(pos, ""), "grade": grade,
                "particleCount": None, "componentHours": None, "oilHours": None,
                "comment": None, "photo": photo,
            })
    return records


def write_data(records):
    inspections = list(records.values())
    for r in inspections:
        r["positions"].sort(key=lambda p: p["key"])
    inspections.sort(key=lambda r: (r["equipment"], r["date"] or ""))
    equipment = sorted({r["equipment"] for r in inspections})
    payload = {"component": "Magnetic Plug", "assetClass": "from photo folder",
               "generated": None, "equipmentList": equipment, "inspections": inspections}
    os.makedirs(os.path.dirname(DATA_FILE), exist_ok=True)
    header = ("// AUTO-GENERATED by ingest/scan_photos.py -- do not edit by hand.\n"
              "// Re-run the scanner to refresh. Loaded by dashboard/index.html.\n")
    with open(DATA_FILE, "w", encoding="utf-8") as fh:
        fh.write(header + "window.CM_DATA = " + json.dumps(payload, ensure_ascii=False, indent=2) + ";\n")
    return equipment, inspections


def main():
    ap = argparse.ArgumentParser(description="Build dashboard data by scanning a photo folder.")
    ap.add_argument("folder", help="Path to the photos root folder.")
    ap.add_argument("--copy", action="store_true",
                    help="Copy photos into assets/photos/ (default: reference them where they are).")
    args = ap.parse_args()
    if not os.path.isdir(args.folder):
        sys.exit(f"Not a folder: {args.folder}")

    records = scan(args.folder, args.copy)
    if not records:
        sys.exit("No photos found. Expected e.g. TK146/2026-10-15/4C.jpg")
    equipment, inspections = write_data(records)
    print(f"Scanned {args.folder}")
    print(f"  {len(equipment)} unit(s), {len(inspections)} inspection(s) -> {DATA_FILE}")
    if not args.copy:
        print("  Photos referenced in place (absolute paths). Use --copy to bundle them.")


if __name__ == "__main__":
    main()
